name: 01 - Hello

on:
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions!"

      - name: Fecha del runner
        run: date

      - name: Archivos disponibles
        run: ls -la

  repo-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v6

      - name: Archivos disponibles del repositorio
        run: ls -la
