name: 02 - Manual

on:
  workflow_dispatch:
    inputs:
      logging_level:
        description: "Nivel de log"
        required: true
        default: "info"
        type: choice
        options:
          - INFO
          - DEBUG
          - WARN
          - ERROR

      environment:
        description: "Entorno de despliegue"
        type: environment
        required: true

      dry_run:
        description: "Ejecutar sin aplicar cambios"
        default: false
        type: boolean

      reason:
        description: "Motivo de la ejecución"
        default: "Manual execution"
        type: string

jobs:
  manual:
    runs-on: ubuntu-24.04
    steps:
      - name: Imprimir los inputs
        env:
          LOG_LEVEL: ${{ inputs.logging_level }}
          ENVIRONMENT: ${{ inputs.environment }}
          DRY_RUN: ${{ inputs.dry_run }}
          REASON: ${{inputs.reason}}
        run: |
          echo "LOG_LEVEL: $LOG_LEVEL"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "DRY_RUN: $DRY_RUN"
          echo "REASON: $REASON"

      - name: Deploy
        if: ${{ !inputs.dry_run  }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Deploying to: $ENVIRONMENT"

      - name: Solo cuando dry_run es true
        if: ${{ inputs.dry_run }}
        env:
          DRY_RUN: ${{ inputs.dry_run }}
        run: |
          echo "dry-run: no changes"
