name: 03 - Schedule

on:
  # schedule:
  #   # Las posiciones indican: minuto - hora - día del mes - mes - día de la semana
  #   - cron: "0 9 * * MON"
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludo
        run: echo "Hola desde GitHub Actions!"
